global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'training-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['training-service:4243']

  - job_name: 'forecast-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['forecast-service:4242']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8089']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']